### ISSUE TITLE
Add stonecutter recipes for items that are being cut with a sword 

### ISSUE THREAD

**Issue by He-Is-Man** [hugeblank/Bagels_Baking#10]
We discussed adding another option to craft items such as chicken nuggets and fries. One way would be to put it in crafting bench with a sword, but this way would be to simply add the item to the stonecutter and it would output that option

Nuggets
Fries
Salt

**Comment by hugeblank** [comment]
closed in 5da767c7651b225ac377d2259b5a8e312811c5c6
