### ISSUE TITLE
Recipe Book Support

### ISSUE THREAD

**Issue by hugeblank** [hugeblank/Bagels_Baking#12]
Does the Recipe book properly unlock foods when you get the materials to craft them? If not we're going to have to investigate adding support for all of the existing items and items to come

**Comment by roger109z** [comment]
You get the recipe added when you craft it for the first time, is this that far off from the desired functionality?

**Comment by hugeblank** [comment]
no, it's not but I feel like we should look into this

**Comment by hugeblank** [comment]
I'm putting some emphasis on this one because I really can't remember how to make a damn brownie and now have to check the mod files lol
