### ISSUE TITLE
Sword duplication when crafting chicken nuggets

### ISSUE THREAD

**Issue by roger109z** [hugeblank/Bagels_Baking#13]
when you craft chicken nuggets you can pull two swords back out of the crafting table

**Comment by hugeblank** [comment]
all I see is pain

**Comment by hugeblank** [comment]
Looking further into this I find that the sword doesn't get duplicated, it seems to just be a client artifact. Can you verify this?

**Comment by roger109z** [comment]
It seems like if you shift click it out then it duplicates and if you drag it out it's a client artifact? Further testing required

**Comment by roger109z** [comment]
ok after testing it some more sometimes the sword duplicates sometimes it doesn't seems very random

**Comment by hugeblank** [comment]
So here's my stop-gap solution. I'm just gonna remove the code that does the sword crafty thingy. I worked on it all day yesterday and today but the stone cutter route is very comedic and effective. It also opens up the option for multiple recipes using just a chicken or just a potato.
