### ISSUE TITLE
Meringue created by brewing with sugar in brewing stand

### ISSUE THREAD

**Issue by hugeblank** [hugeblank/Bagels_Baking#22]
Replace current behavior with this, would be less buggy and fix #18

**Comment by roger109z** [comment]
Looked into adding this functionality and it seems like the brewing stand will only accept items that are potions as recipe ingredients it might be possible to typecast a cooked egg as an item and pass it to the recipe I will have to look into it further

**Comment by hugeblank** [comment]
it's not a cooked egg we want it's the raw egg whites, I'll look into it too

**Comment by hugeblank** [comment]
~~oh wait yeah it's sugar into raw egg whites we can do this~~
