### ISSUE TITLE
More Drinks

### ISSUE THREAD

**Issue by hugeblank** [hugeblank/Bagels_Baking#23]
It was discussed on Hunter's [stream](https://www.twitch.tv/videos/880620364) yesterday that lots more drinkable items should be brought into the mod. Those discussed were:

- [x] Chocolate Milk
- [x] Sodas
- [x] Coffee

**Comment by roger109z** [comment]
all of the vanilla drinkables don't refill any hunger or saturation, will the new drinks have the same treatment?

**Comment by hugeblank** [comment]
> 
> 
> all of the vanilla drinkables don't refill any hunger or saturation, will the new drinks have the same treatment?

I think they should, albeit not as filling as the regular food items.
