### ISSUE TITLE
Brohh add milk glass because garfield got milk

### ISSUE THREAD

**Issue by fatboychummy** [hugeblank/Bagels_Baking#28]
The idea is that, in a crafting table, place a bucket of milk with 8 cups surrounding it. The result is 8 cups of milk. Drinking a cup of milk will only remove a single status effect instead of all status effects when drank, however.

Further crafting recipes can be used with the cups of milk.

**Comment by hugeblank** [comment]
Cups are crafted from iron nuggets in the same way that buckets are
